# CMSC 197 (ML) - HW1
Import numpy package to use in project

In [1]:
import numpy as np

## Part 1: Create 2 2D arrays, y_hat and y
Initialize y_hat with 20 linearly spaced numbers between -1 and 1

In [2]:
y_hat = np.linspace(-1, 1, num=20)
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

Initialize y with 20 linearly spaced numbers between 0 and 1

In [3]:
y = np.linspace(0, 1, num=20)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Compute for the shape and dimension of y_hat

In [4]:
y_hat.shape

(20,)

In [5]:
y_hat.ndim

1

Compute for the shape and dimension of y

In [6]:
y.shape

(20,)

In [7]:
y.ndim

1

## Create individual functions for each of the loss functions with y and y_hat as parameters
### Mean Squared Error:
Compute for $L = \frac{\sum_{i=1}^{N}(\hat{y}-y)^2}{N}$ by taking the array difference, squaring it, and taking the resulting mean.

In [8]:
def mse():
    result = np.mean(np.power((y_hat-y),2))
    return result

In [9]:
print(mse())

0.3421052631578948


### Mean Absolute Error:
Compute for $L = \frac{\sum_{i=1}^{n}|\hat{y}-y|}{n}$ by taking the absolute value of each element of the array difference between $\hat{y}$ and $y$, taking the resulting mean.

In [10]:
def mae():
    result = np.mean(abs(y_hat-y))
    return result

In [11]:
print(mae())

0.4999999999999999


### Mean Squared Logarithmic Error:
Compute for $L = \frac{\sum_{i=1}^{n}(\log(\hat{y}+1)-\log(y+1))^2}{n}$ by squaring each element of the array difference between $\log(\hat{y}+1)$ and $\log(y+1)$, taking the resulting mean.

In [12]:
def msle():
    result = np.mean(np.power((np.log1p(y_hat+1) - np.log1p(y+1)),2))
    return result

In [13]:
print(msle())

0.1125199374308555


### Mean Absolute Percentage Error:
Compute for $L = \frac{100\%}{n} \sum_{i=1}^{n}|\frac{\hat{y}-y}{y}|$ by solving for the absolute value of the array difference between $\hat{y}$ and $y$, dividing the resulting array by $y$, finding its resulting mean, and multiplying it by 100%.

In [14]:
def mape():
    result = np.mean(abs((y_hat-y)/y_hat))*100
    return result

In [15]:
print(mape())

202.65927536515775


## Part 2: Create a 1d array M {1, 2, ...16} using the arange function

In [16]:
M = np.arange(1,17)

In [17]:
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Reshape M into 4x4 array and store it to N

In [18]:
N = np.reshape(M,(4,4))

In [19]:
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Get the 2nd row of N

In [20]:
N[1]

array([5, 6, 7, 8])

Get the minimum values for each column of N

In [21]:
np.min(N, axis=0)

array([1, 2, 3, 4])

Get the locations of the minimum values for each column of N

In [22]:
result = np.where(N == np.min(N, axis=0))
for i in list(zip(result[0],result[1])):
    print(i)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


Get the average of the whole matrix

In [23]:
np.mean(N)

8.5

Create a vector V with 4 elements, each element is 1

In [24]:
V = np.ones(4)

In [25]:
V

array([1., 1., 1., 1.])

Take the dot product of N and V

In [26]:
np.dot(N, V)

array([10., 26., 42., 58.])